### ISSUE TITLE
Consider not calling physical properties legacy

### ISSUE THREAD

**Issue by pepelsbey** [mayank99/postcss-use-logical#1]
Throughout the readme and website itself, properties like margin-left are called not only “physical”, but also “legacy”, which is not exactly correct. [According to the spec](https://drafts.csswg.org/css-logical/):

> These properties are writing-mode relative equivalents of their corresponding physical properties.

> Documents might need both logical and physical properties. For instance the drop shadows on buttons on a page must remain consistent throughout, so their offset will be chosen based on visual considerations and physical directions, and not vary by writing system.

It would be incorrect to assume that logical properties would supersede, replace, or make physical properties less relevant.

I’d suggest calling physical properties what they are to make this great tool less opinionated and keep it closer to the idea behind the spec.

**Comment by mayank99** [comment]
Hey @pepelsbey, thanks for the issue. There may be a misunderstanding as I'm not calling physical properties themselves "legacy". It is the source code as a whole that is called "legacy".

https://github.com/mayank99/postcss-use-logical/blob/862b0cc76e60ec30137d25f704ffeee69465aa84/README.md?plain=1#L9

https://github.com/mayank99/postcss-use-logical/blob/862b0cc76e60ec30137d25f704ffeee69465aa84/website/src/routes/%2Bpage.svelte#L35

The idea is that the source code was written before logical properties were usable, and would not be written the same way today, therefore making it legacy.

The spec makes a good point though - it may not be desirable to convert *everything* to logical properties. So this plugin does *too much* in a way.

Let me know if you have any suggestions for alternative naming too. Maybe "old code"?

Or I could rephrase the whole thing and mention this exact caveat.

**Comment by pepelsbey** [comment]
Oh, sorry for misunderstanding. It’s good to know that you’re not considering them legacy :)

I wouldn’t call a code that uses physical properties “old” either. It might be less flexible or RTL-only, which is fine.

I’d focus on what the plugin does: it converts physical properties into logical ones. And that’s it: not bad to good, not old to new, not legacy to modern.

Something like this?

> Input: physical properties (CSS/SCSS)
> Output: logical properties
